# This determines the command prefix when there are conflicts (/name:home, /name:help, etc.)
name: Essentials
main: com.earth2me.essentials.Essentials
# Note to developers: This next line cannot change, or the automatic versioning system will break.
version: ${project.version}-b${build.number}
website: http://tiny.cc/EssentialsCommands
description: Provides an essential, core set of commands for Bukkit.
softdepend: [Vault]
authors: [Zenexer, ementalo, Aelux, Brettflan, KimKandor, snowleo, ceulemans, Xeology, KHobbits, md_5, Iaccidentally, drtshock, vemacs, SupaHam, md678685]
commands:
  afk:
    description: Marks you as away-from-keyboard.
    usage: /<command> [player/message...]
    aliases: [eafk,away,eaway]
  #antioch:
  #  description: 'A little surprise for operators.'
  #  usage: /<command> [message]
  #  aliases: [eantioch,grenade,egrenade,tnt,etnt]
  back:
    description: Teleports you to your location prior to tp/spawn/warp.
    usage: /<command>
    aliases: [eback,return,ereturn]
  #backup:
  #  description: Runs the backup if configured.
  #  usage: /<command>
  #  aliases: [ebackup]
  balance:
    description: States the current balance of a player.
    usage: /<command> [player]
    aliases: [bal,ebal,ebalance,money,emoney]
  balancetop:
    description: Gets the top balance values.
    usage: /<command> <page>
    aliases: [ebalancetop,baltop,ebaltop]
  #ban:
  #  description: Bans a player.
  #  usage: /<command> <player> [reason]
  #  aliases: [eban]
  #banip:
  #  description: Bans an IP address.
  #  usage: /<command> <address>
  #  aliases: [ebanip]
  #book:
  #  description: Allows reopening and editing of sealed books.
  #  usage: /<command> [title|author [name]]
  #  aliases: [ebook]
  break:
    description: Breaks the block you are looking at.
    usage: /<command>
    aliases: [ebreak]
  #broadcast:
  #  description: Broadcasts a message to the entire server.
  #  usage: /<command> <msg>
  #  aliases: [bc,ebc,bcast,ebcast,ebroadcast,shout,eshout]
  #broadcastworld:
  #  description: Broadcasts a message to a world.
  #  usage: /<command> <world> <msg>
  #  aliases: [bcw,ebcw,bcastw,ebcastw,ebroadcastworld,shoutworld,eshoutworld]
  #bigtree:
  #  description: Spawn a big tree where you are looking.
  #  usage: /<command> <tree|redwood|jungle>
  #  aliases: [ebigtree,largetree,elargetree]
  burn:
    description: Set a player on fire.
    usage: /<command> <player> <seconds>
    aliases: [eburn]
  clearinventory:
    description: Clear all items in your inventory.
    usage: /<command> [player|*] [item[:<data>]|*|**] [amount]
    aliases: [ci,eci,clean,eclean,clear,eclear,clearinvent,eclearinvent,eclearinventory]
  clearinventoryconfirmtoggle:
    description: Toggles whether you are prompted to confirm inventory clears.
    usage: /<command>
    aliases: [eclearinventoryconfirmtoggle, clearinventoryconfirmoff, eclearinventoryconfirmoff, clearconfirmoff, eclearconfirmoff, clearconfirmon, eclearconfirmon, clearconfirm, eclearconfirm]
  condense:
    description: Condenses items into a more compact blocks.
    usage: /<command> [<itemname>|<id>|hand|inventory]
    aliases: [econdense,compact,ecompact,blocks,eblocks,toblocks,etoblocks]
  compass:
    description: Describes your current bearing.
    usage: /<command>
    aliases: [ecompass,direction,edirection]
  #createkit:
  #  description: Create a kit in game!
  #  usage: /<command> <kitname> <delay>
  #  aliases: [kitcreate,createk,kc,ck]
  #customtext:
  #  description: Allows you to create custom text commands.
  #  usage: /<alias> - Define in bukkit.yml
  delhome:
    description: Removes a home.
    usage: /<command> [player:]<name>
    aliases: []
  deljail:
    description: Removes a jail.
    usage: /<command> <jailname>
    aliases: []
  delwarp:
    description: Deletes the specified warp.
    usage: /<command> <warp>
    aliases: []
  depth:
    description: States current depth, relative to sea level.
    usage: /depth
    aliases: [height]
  eco:
    description: Manages the server economy.
    usage: /<command> <give|take|set|reset> <player> <amount>
    aliases: [economy]
  enchant:
    description: Enchants the item the user is holding.
    usage: /<command> <enchantmentname> [level]
    aliases: [enchantment]
  enderchest:
    description: Lets you see inside an enderchest.
    usage: /<command> [player]
    aliases: [ec,eec]
  essentials:
    description: Reloads essentials.
    usage: /<command>
    aliases: [ess]
  exp:
    description: Give, set or look at a players exp.
    usage: /<command> [show|set|give] [playername [amount]]
    aliases: [xp]
  ext:
    description: Extinguish players.
    usage: /<command> [player]
    aliases: [extinguish]
  feed:
    description: Satisfy the hunger.
    usage: /<command> [player]
    aliases: [eat]
  fly:
    description: Take off, and soar!
    usage: /<command> [player] [on|off]
    aliases: [адн]
  #fireball:
  #  description: Throw a fireball.
  #  usage: /<command> [small|skull]
  #  aliases: [efireball,fireentity,efireentity,fireskull,efireskull]
  firework:
    description: Allows you to modify a stack of fireworks.
    usage: /<command> <<meta param>|power [amount]|clear|fire [amount]>
  gamemode:
    description: Change player gamemode.
    usage: /<command> <survival|creative|adventure|spectator> [player]
    aliases: [adventure,adventuremode,creative,creativemode,gm,gma,gmc,gms,gmt,survival,survivalmode,gmsp,sp,spec,spectator]
  gc:
    description: Reports memory, uptime and tick info.
    usage: /<command> [all]
  getpos:
    description: Get your current coordinates or those of a player.
    usage: /<command> [player]
    aliases: [coords,position]
  give:
    description: Give a player an item.
    usage: /<command> <player> <item|numeric> [amount [itemmeta...]]
  god:
    description: Enables your godly powers.
    usage: /<command> [player] [on|off]
    aliases: [godmode]
  hat:
    description: Get some cool new headgear.
    usage: /<command> [remove]
  heal:
    description: Heals you or the given player.
    usage: /<command> [player]
  #help:
  #  description: Views a list of available commands.
  #  usage: /<command> [search term] [page]
  #  aliases: [ehelp]
  #helpop:
  #  description: Message online admins.
  #  usage: /<command> <message>
  #  aliases: [ac,eac,amsg,eamsg,ehelpop]
  home:
    description: Teleport to your home.
    usage: /<command> [player:][name]
    aliases: [h,р,рщьу,homes]
  ignore:
    description: Ignore or unignore other players.
    usage: /<command> <player>
  #info:
  #  description: Shows information set by the server owner.
  #  usage: /<command> [chapter] [page]
  #  aliases: [about,eabout,ifo,eifo,einfo,inform,einform,news,enews]
  invsee:
    description: See the inventory of other players.
    usage: /<command> <player>
  item:
    description: Spawn an item.
    usage: /<command> <item|numeric> [amount [itemmeta...]]
  itemdb:
    description: Searches for an item.
    usage: /<command> <item>
  jails:
    description: List all jails.
    usage: /<command>
  jump:
    description: Jumps to the nearest block in the line of sight.
    usage: /<command>
    aliases: [j,jumpto]
  #kick:
  #  description: Kicks a specified player with a reason.
  #  usage: /<command> <player> [reason]
  #  aliases: [ekick]
  #kickall:
  #  description: Kicks all players off the server except the issuer.
  #  usage: /<command> [reason]
  #  aliases: [ekickall]
  #kill:
  #  description: Kills specified player.
  #  usage: /<command> <player>
  #  aliases: [ekill]
  #kit:
  #  description: Obtains the specified kit or views all available kits.
  #  usage: /<command> [kit] [player]
  #  aliases: [ekit,kits,ekits]
  #kittycannon:
  #  description: Throw an exploding kitten at your opponent.
  #  usage: /<command>
  #  aliases: [ekittycannon]
  #lightning:
  #  description: The power of Thor. Strike at cursor or player.
  #  usage: /<command> [player] [power]
  #  aliases: [elightning,shock,eshock,smite,esmite,strike,estrike,thor,ethor]
  list:
    description: List all online players.
    usage: /<command> [group]
    aliases: [elist,online,eonline,playerlist,eplayerlist,plist,eplist,who,ewho]
  mail:
    description: Manages inter-player, intra-server mail.
    usage: /<command> [read|clear|send [to] [message]|sendall [message]]
    aliases: [email,eemail,memo,ememo]
  #me:
  #  description: Describes an action in the context of the player.
  #  usage: /<command> <description>
  #  aliases: [action,eaction,describe,edescribe,eme]
  more:
    description: Fills the item stack in hand to maximum size.
    usage: /<command>
    aliases: [dupe]
  #motd:
  #  description: Views the Message Of The Day.
  #  usage: /<command> [chapter] [page]
  #  aliases: [emotd]
  msg:
    description: Sends a private message to the specified player.
    usage: /<command> <to> <message>
    aliases: [w,m,t,tell]
  msgtoggle:
    description: Blocks receiving all private messages.
    usage: /<command> [player] [on|off]3
  mute:
    description: Mutes or unmutes a player.
    usage: /<command> <player> [datediff]
  near:
    description: Lists the players near by or around a player.
    usage: /<command> [playername] [radius]
  #nick:
  #  description: Change your nickname or that of another player.
  #  usage: /<command> [player] <nickname|off>
  #nuke:
  #  description: May death rain upon them.
  #  usage: /<command> [player]
  #  aliases: [enuke]
  pay:
    description: Pays another player from your balance.
    usage: /<command> <player> <amount>
    aliases: [epay]
  paytoggle:
    description: Toggles whether you are accepting payments.
    usage: /<command>
    aliases: [epaytoggle, payoff, epayoff, payon, epayon]
  payconfirmtoggle:
    description: Toggles whether you are prompted to confirm payments.
    usage: /<command>
    aliases: [epayconfirmtoggle, payconfirmoff, epayconfirmoff, payconfirmon, epayconfirmon, payconfirm, epayconfirm]
  #ping:
  #  description: Pong!
  #  usage: /<command>
  #  aliases: [echo,eecho,eping,pong,epong]
  potion:
    description: Adds custom potion effects to a potion.
    usage: /<command> <clear|apply|effect:<effect> power:<power> duration:<duration>>
    aliases: [epotion,elixer,eelixer]
  powertool:
    description: Assigns a command to the item in hand.
    usage: /<command> [l:|a:|r:|c:|d:][command] [arguments] - {player} can be replaced by name of a clicked player.
    aliases: [pt]
  #powertooltoggle:
  #  description: Enables or disables all current powertools.
  #  usage: /<command>
  #  aliases: [epowertooltoggle,ptt,eptt,pttoggle,epttoggle]
  ptime:
    description: Adjust player's client time. Add @ prefix to fix.
    usage: /<command> [list|reset|day|night|dawn|17:30|4pm|4000ticks] [player|*]
    aliases: [playertime]
  pweather:
    description: Adjust a player's weather
    usage: /<command> [list|reset|storm|sun|clear] [player|*]
    aliases: [playerweather]
  r:
    description: Quickly reply to the last player to message you.
    usage: /<command> <message>
    aliases: [reply]
  realname:
    description: Displays the username of a user based on nick.
    usage: /<command> <nickname>
  recipe:
    description: Displays how to craft items.
    usage: /<command> <item> [number]
  remove:
    description: Removes entities in your world.
    usage: /<command> <all|tamed|named|drops|arrows|boats|minecarts|xp|paintings|itemframes|endercrystals|monsters|animals|ambient|mobs|[mobType]> [radius|world]
    aliases: [killall]
  repair:
    description: Repairs the durability of one or all items.
    usage: /<command> [hand|all]
    aliases: [fix]
  #rules:
  #  description: Views the server rules.
  #  usage: /<command> [chapter] [page]
  #  aliases: [erules]
  #seen:
  #  description: Shows the last logout time of a player.
  #  usage: /<command> <playername>
  #  aliases: [eseen]
  #sell:
  #  description: Sells the item currently in your hand.
  #  usage: /<command> <<itemname>|<id>|hand|inventory|blocks> [-][amount]
  #  aliases: [esell]
  sethome:
    description: Set your home to your current location.
    usage: /<command> [[player:]name]
    aliases: [esethome,createhome,ecreatehome]
  setjail:
    description: Creates a jail where you specified named [jailname].
    usage: /<command> <jailname>
    aliases: [esetjail,createjail,ecreatejail]
  setwarp:
    description: Creates a new warp.
    usage: /<command> <warp>
    aliases: [createwarp,ecreatewarp,esetwarp]
  #setworth:
  #  description: Set the sell value of an item.
  #  usage: /<command> [itemname|id] <price>
  #  aliases: [esetworth]
  #showkit:
  #  description: Show contents of a kit.
  #  usage: /<command> <kitname>
  #  aliases: [kitpreview,preview,kitshow]
  skull:
    description: Set the owner of a player skull
    usage: /<command> [owner]
    aliases: [head]
  socialspy:
    description: Toggles if you can see msg/mail commands in chat.
    usage: /<command> [player] [on|off]
  spawner:
    description: Change the mob type of a spawner.
    usage: /<command> <mob> [delay]
    aliases: [changems,echangems,espawner,mobspawner,emobspawner]
  spawnmob:
    description: Spawns a mob.
    usage: /<command> <mob>[:data][,<mount>[:data]] [amount] [player]
    aliases: [mob,emob,spawnentity,espawnentity,espawnmob]
  speed:
    description: Change your speed limits.
    usage: /<command> [type] <speed> [player]
    aliases: [flyspeed,fspeed,walkspeed,wspeed]
  sudo:
    description: Make another user perform a command.
    usage: /<command> <player> <command [args]>
  suicide:
    description: Causes you to perish.
    usage: /<command>
  #tempban:
  #  description: Temporary ban a user.
  #  usage: /<command> <playername> <datediff> <reason>
  thunder:
    description: Enable/disable thunder.
    usage: /<command> <true/false> [duration]
  time:
    description: Display/Change the world time. Defaults to current world.
    usage: /<command> [day|night|dawn|17:30|4pm|4000ticks] [worldname|all]
    aliases: [day,night]
  togglejail:
    description: Jails/Unjails a player, TPs them to the jail specified.
    usage: /<command> <player> <jailname> [datediff]
    aliases: [jail,tjail,unjail]
  top:
    description: Teleport to the highest block at your current position.
    usage: /<command>
  tp:
    description: Teleport to a player.
    usage: /<command> <player> [otherplayer]
    aliases: [tele,etele,teleport,eteleport,etp,tp2p,etp2p]
  tpa:
    description: Request to teleport to the specified player.
    usage: /<command> <player>
    aliases: [call,tpask]
  #tpaall:
  #  description: Requests all players online to teleport to you.
  #  usage: /<command> <player>
  tpaccept:
    description: Accepts a teleport request.
    usage: /<command> [otherplayer]
    aliases: [tpyes]
  tpahere:
    description: Request that the specified player teleport to you.
    usage: /<command> <player>
  tpall:
    description: Teleport all online players to another player.
    usage: /<command> <player>
  tpacancel:
    description: Cancel all outstanding teleport requests. Specify [player] to cancel requests with them.
    usage: /<command> [player]
  tpdeny:
    description: Reject a teleport request.
    usage: /<command>
    aliases: [tpno]
  tphere:
    description: Teleport a player to you.
    usage: /<command> <player>
  tpo:
    description: Teleport override for tptoggle.
    usage: /<command> <player> [otherplayer]
  tpohere:
    description: Teleport here override for tptoggle.
    usage: /<command> <player>
  tppos:
    description: Teleport to coordinates.
    usage: /<command> <x> <y> <z> [yaw] [pitch] [world]
  tptoggle:
    description: Blocks all forms of teleportation.
    usage: /<command> [player] [on|off]
  #tree:
  #  description: Spawn a tree where you are looking.
  #  usage: /<command> <tree|birch|redwood|redmushroom|brownmushroom|jungle|junglebush|swamp>
  #  aliases: [etree]
  #unban:
  #  description: Unbans the specified player.
  #  usage: /<command> <player>
  #  aliases: [pardon,eunban,epardon]
  #unbanip:
  #  description: Unbans the specified IP address.
  #  usage: /<command> <address>
  #  aliases: [eunbanip,pardonip,epardonip]
  unlimited:
    description: Allows the unlimited placing of items.
    usage: /<command> <list|item|clear> [player]
    aliases: [eunlimited,ul,unl,eul,eunl]
  vanish:
    description: Hide yourself from other players.
    usage: /<command> [player] [on|off]
  warp:
    description: List all warps or warp to the specified location.
    usage: /<command> <pagenumber|warp> [player]
    aliases: [warps]
  weather:
    description: Sets the weather.
    usage: /<command> <storm/sun> [duration]
    aliases: [rain,sky,storm,sun]
  #whois:
  #  description: Determine the username behind a nickname.
  #  usage: /<command> <nickname>
  workbench:
    description: Opens up a workbench.
    usage: /<command>
    aliases: [wb]
  world:
    description: Switch between worlds.
    usage: /<command> [world]
  worth:
    description: Calculates the worth of items in hand or as specified.
  glow:
    usage: /<command> [nick]

permissions:
  essentials.*:
    default: op
    description: Give players with op everything by default
    children:
      essentials.gamemode.*: true
  # These permissions can't be assigned from player-commands for compatibility reasons
  essentials.teleport.cooldown.bypass.tpa:
    default: true
    description: If the player does not have this permission, /tpa will have cooldown even with the parent bypass perm
  essentials.teleport.cooldown.bypass.back:
    default: true
    description: If the player does not have this permission, /back will have cooldown even with the parent bypass perm
  essentials.gamemode.*:
    default: op
    children:
      essentials.gamemode: true
      essentials.gamemode.others: true
      essentials.gamemode.all: true
